version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
